"""pack: journal — macro-recorder over the design ops (start/stop/show/clear/script).

The journal STATE + capture hook live in _core (bridge.eval needs them); this pack
just exposes the control tool.
"""
import json
from _core import mcp, GimpError, _JOURNAL


@mcp.tool
def journal(action: str = "show", label: str = "", path: str = "") -> str:
    """Record/replay the design ops you run — a macro recorder for the session.

    action:
      start  → begin recording (optional label); clears the previous log
      stop   → pause recording
      show   → list the recorded ops
      clear  → wipe the log
      script → write a standalone replay .py to `path` (default /tmp/gimp-journal.py)
    Pure queries and preview/export scratch are filtered out automatically, so the log
    reads like a recipe. Turn a recording into a reusable recipe with
    save_recipe(from_journal=True, image_id=<id>).
    """
    a = action.lower().strip()
    if a == "start":
        _JOURNAL.update(on=True, label=label, ops=[])
        return f"journal recording{f' [{label}]' if label else ''} — run your edits, then `journal show` / save_recipe."
    if a == "stop":
        _JOURNAL["on"] = False
        return f"journal paused — {len(_JOURNAL['ops'])} ops recorded."
    if a == "clear":
        _JOURNAL["ops"] = []
        return "journal cleared."
    if a == "show":
        ops = _JOURNAL["ops"]
        head = f"journal [{_JOURNAL['label']}]  recording={_JOURNAL['on']}  {len(ops)} ops"
        return head + (":\n" + "\n".join(f"{i:3}: {s}" for i, s in enumerate(ops)) if ops else " (empty)")
    if a == "script":
        p = path or "/tmp/gimp-journal.py"
        ops = [s for s in _JOURNAL["ops"] if not s.strip().startswith(";")]
        body = "\n".join(f"    ev({json.dumps(s)})" for s in ops) or "    pass"
        script = (
            "#!/usr/bin/env python3\n"
            '"""Replay of a gimp-mcp session. Start the Script-Fu server, load your\n'
            'source image, set IMG, then run. Generated by gimp-mcp `journal script`."""\n'
            "import os, sys\n"
            "sys.path.insert(0, os.path.expanduser('~/projects/gimp-mcp'))\n"
            "from gimp_bridge import GimpBridge\n"
            "b = GimpBridge(); ev = lambda s: b.eval(s).strip()\n"
            "IMG = 1  # <- set to your image id\n\n"
            "def run():\n" + body + "\n\n"
            "if __name__ == '__main__':\n    run()\n"
        )
        with open(p, "w") as f:
            f.write(script)
        return f"wrote replay script ({len(ops)} ops) -> {p}"
    raise GimpError(f"unknown action '{action}' — use start | stop | show | clear | script")
